AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}

  Sample SAM Template for {{ cookiecutter.project_name }}
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DyanamoDBTypescript:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      
      Architectures:
         - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /empdata
            Method: post
        GetData:
          Type: Api
          Properties:
            Path: /empdata
            Method: get
      Policies:
         DynamoDBCrudPolicy:
             TableName: !Ref UserTable
 
      
  
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
        
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: typescript-sam-dynamodb
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
       - AttributeName: id
         KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
 
  DynamoDBOperation:
    Description: "API Gateway endpoint URL for Prod stage for Dynamodb operation function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
 
